
font_family     0xProto
scrollback_lines 8000
shell zsh
enable_audio_bell no
tab_bar_style fade
tab_bar_align center
tab_fade 0
tab_title_template "{index}:{tab.active_exe}"
active_tab_foreground   #fff
inactive_tab_foreground #444
inactive_tab_background #000
active_tab_background #000
confirm_os_window_close 0 
